version: '3.4'

services:
  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    ports:
        - "8000:80"
    build:
      context: .
      dockerfile: src/CatalogService/CatalogService.Api/Dockerfile
    depends_on:
        - "db"
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest",
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Password4598.",
        ACCEPT_EULA: "Y"
    