version: '3.4'

services:
  catalogservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  basketservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis_ExternalIpAddress=172.21.144.1 # This Code Line For Redis External Ip Address not Localhost
    ports:
      - "80"
      
