version: '3.4'

services:
  catalogservice.api:
    container_name: catalog_service
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    ports:
        - "53472:80"
    build:
      context: .
      dockerfile: src/CatalogService/CatalogService.Api/Dockerfile
    depends_on:
        - catalog_database
  basketservice.api:
    container_name: basket_service
    image: ${DOCKER_REGISTRY-}basketserviceapi
    ports:
        - "53471:80"
    build:
      context: .
      dockerfile: src/BasketService/BasketService.Api/Dockerfile
    depends_on:
        - redis_database
  catalog_database:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
          - "1433:1433"
        container_name: sql_server_container
        environment:
            SA_PASSWORD: "Password4598."
            ACCEPT_EULA: "Y"
        volumes:
            - ./src/CatalogService/sql-volume:/var/opt/mssql/data
  redis_database:
        image: "redis:alpine"
        ports:
          - "6379:6379"
        container_name: redis_container
        volumes:
            - ./src/BasketService/redis-volume:/data
  discount_database:
        image: "postgres:latest"
        environment:
          PGDATA: /var/lib/postgresql/data/discount_data/
  pgadmin:
        image: "dpage/pgadmin4"
  portainer:
        image: "portainer/portainer-ce"
        ports:
          - "8080:8000"
          - "9000:9000"
        container_name: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer_data:/data
  discountservice.api:
    image: ${DOCKER_REGISTRY-}discountserviceapi
    build:
      context: .
      dockerfile: src/DiscountService/DiscountService.Api/Dockerfile
  