version: '3.4'

services:
  catalogservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  basketservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis_ExternalIpAddress=172.30.16.1 # This Code Line For Redis External Ip Address not Localhost
    ports:
      - "80"
  discount_database:
    container_name: "discountdb"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
  pgadmin:
    container_name: "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/root/.pgadmin
  discountservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

