version: '3.4'

services:
  catalogservice.api:
    container_name: catalog_service
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    ports:
        - "53472:80"
    build:
      context: .
      dockerfile: src/CatalogService/CatalogService.Api/Dockerfile
    depends_on:
        - catalog_database
  catalog_database:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
          - "1433:1433"
        container_name: sql_server_container
        environment:
            SA_PASSWORD: "Password4598."
            ACCEPT_EULA: "Y"
        volumes:
            - ./sql-volume:/var/opt/mssql/data